package Objets;

class Donnees{

    static final String[] VILLES = { 
		"Vancouver 94.0 15.0",
		"Seattle 88.0 52.0",
		"Portland 74.0 88.0",
		"San Francisco 42.0 241.0",
		"Los Angeles 89.0 338.0",
		"Las Vegas 153.0 302.0",
		"Calgary 259.0 15.0", // CA
		"Salt Lake City 224.0 216.0",
		"Phoenix 192.0 348.0",
		"Helena 247.0 90.0",
		"Denver 332.0 255.0",
		"Santa Fe 310.0 340.0",
		"El Paso 294.0 422.0",
		"Winnipeg 484.0 50.0",  // CA
		"Duluth 538.0 102.0",
		"Omaha 479.0 225.0",
		"Kansas City 509.0 273.0",
		"Oklahoma City 456.0 343.0",
		"Dallas 473.0 414.0",
		"Houston 494.0 475.0",
		"Saint Louis 593.0 299.0",
		"Little Rock 549.0 378.0",
		"Sault Saint Marie 655.0 101.0",  // CA
		"Chicago 665.0 188.0",
		"New Orleans 592.0 471.0",
		"Nashville 642.0 330.0",
		"Atlanta 694.0 376.0",
		"Toronto 745.0 156.0", // CA
		"Pittsburgh 748.0 213.0", 
		"Miami 797.0 537.0", 
		"Montreal 809.0 98.0",  // CA
		"Raleigh 786.0 317.0",
		"Charleston 773.0 384.0", 
		"New York 842.0 199.0", 
		"Washington 808.0 244.0",
		"Boston 876.0 150.0"
	};
	
	static final String[][] ROUTES = { 
			{"Vancouver", "Seattle", "gris"},
			{"Vancouver", "Calgary", "gris"},
			{"Seattle", "Portland",  "gris"},
			{"Seattle", "Calgary", "gris"},
			{"Seattle", "Helena", "jaune"},
			{"Portland", "San Francisco", "vert"},
			{"Portland", "Salt Lake City", "bleu"},
			{"San Francisco", "Salt Lake City", "orange"},
			{"San Francisco", "Los Angeles", "violet"},
			{"Los Angeles", "Las Vegas", "gris"},
			{"Los Angeles", "Phoenix", "gris"},
			{"Los Angeles", "El Paso", "noir"},
			{"Las Vegas", "Salt Lake City", "orange"},
			{"Calgary", "Winnipeg",  "blanc"},
			{"Calgary", "Helena", "gris"},
			{"Salt Lake City", "Helena", "violet"},
			{"Salt Lake City", "Denver", "rouge"},
			{"Phoenix", "Denver", "blanc"},
			{"Phoenix", "Santa Fe", "gris"},
			{"Phoenix", "El Paso", "gris"},
			{"Helena", "Winnipeg", "bleu"},
			{"Helena", "Duluth", "orange"},
			{"Helena", "Omaha", "rouge"},
			{"Helena", "Denver", "vert"},
			{"Denver", "Omaha", "violet"},
			{"Denver", "Kansas City", "noir"},
			{"Denver", "Santa Fe", "gris"},
			{"Denver", "Oklahoma City", "rouge"},
			{"Santa Fe", "Oklahoma City", "bleu"},
			{"Santa Fe", "El Paso", "gris"},
			{"El Paso", "Oklahoma City", "jaune"},
			{"El Paso", "Dallas", "rouge"},
			{"El Paso", "Houston", "vert"},
			{"Winnipeg", "Duluth", "noir"},
			{"Winnipeg", "Sault Saint Marie", "gris"},
			{"Duluth", "Sault Saint Marie", "gris"},
			{"Duluth", "Toronto", "violet"},
			{"Duluth", "Chicago", "rouge"},
			{"Duluth", "Omaha", "gris"},
			{"Omaha", "Chicago", "bleu"},
			{"Omaha", "Kansas City", "gris"},
			{"Kansas City", "Saint Louis", "bleu"},
			{"Kansas City", "Oklahoma City", "gris"},
			{"Oklahoma City", "Little Rock", "gris"},
			{"Oklahoma City", "Dallas", "gris"},
			{"Dallas", "Little Rock", "gris"},
			{"Dallas", "Houston", "gris"},
			{"Houston", "New Orleans", "gris"},
			{"Saint Louis", "Chicago", "blanc"},
			{"Saint Louis", "Pittsburgh", "vert"},
			{"Saint Louis", "Nashville", "gris"},
			{"Saint Louis", "Little Rock", "gris"},
			{"Little Rock", "Nashville", "blanc"},
			{"Little Rock", "New Orleans", "vert"},
			{"Sault Saint Marie", "Montreal", "noir"},
			{"Sault Saint Marie", "Toronto", "gris"},
			{"Chicago", "Toronto", "blanc"},
			{"Chicago", "Pittsburgh", "orange"},
			{"New Orleans", "Atlanta", "jaune"},
			{"New Orleans", "Miami", "rouge"},
			{"Nashville", "Pittsburgh", "jaune"},
			{"Nashville", "Raleigh", "noir"},
			{"Nashville", "Atlanta", "gris"},
			{"Atlanta", "Raleigh", "gris"},
			{"Atlanta", "Charleston", "gris"},
			{"Atlanta", "Miami", "bleu"},
			{"Toronto", "Montreal", "gris"},
			{"Toronto", "Pittsburgh", "gris"},
			{"Pittsburgh", "Raleigh", "gris"},
			{"Pittsburgh", "Washington", "gris"},
			{"Pittsburgh", "New York", "blanc"},
			{"Montreal", "Boston", "gris"},
			{"Montreal", "New York", "bleu"},
			{"Raleigh", "Charleston", "gris"},
			{"Raleigh", "Washington", "gris"},
			{"Charleston", "Miami", "violet"},
			{"New York", "Boston", "jaune"},
			{"New York", "Washington", "noir"}
	};

}
